In [1]:
# tensorflow와 tf.keras를 임포트합니다
import tensorflow as tf
from tensorflow import keras
from keras import layers

# 헬퍼(helper) 라이브러리를 임포트합니다
import numpy as np
import matplotlib.pyplot as plt

print(tf.__version__)

2.8.2


## 퍼셉트론

In [2]:
X=np.random.rand(1,5)

In [3]:
# 퍼셉트론의 생성
l=layers.Dense(1,input_shape=[5])

In [4]:
# 퍼셉트론 처리 예시
# 임의의 weight가 할당된 상태
l(X)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[-1.0039166]], dtype=float32)>

## 퍼셉트론 (출력층이 여러개)

In [5]:
l=layers.Dense(3,input_shape=[5])
l(X)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[ 0.27207616, -0.5839657 ,  0.6307751 ]], dtype=float32)>

## 퍼셉트론 (활성화 함수)

In [6]:
l=layers.Dense(3,input_shape=[5],activation='sigmoid')
# l=layers.Dense(3,input_shape=[ 5],activation='tanh')
# l=layers.Dense(3,input_shape=[5],activation='relu')
l(X)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.452923  , 0.6056739 , 0.51846576]], dtype=float32)>

## 한번에 여러 raw 처리

In [7]:
X=np.random.rand(10,5)
l(X)

<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
array([[0.4593271 , 0.5896457 , 0.45497906],
       [0.49431756, 0.57953066, 0.54757583],
       [0.45532125, 0.6554992 , 0.42361438],
       [0.31462115, 0.6944728 , 0.3994269 ],
       [0.3944434 , 0.5763289 , 0.57876235],
       [0.32525906, 0.66332483, 0.5619228 ],
       [0.507813  , 0.63353753, 0.41997024],
       [0.45481247, 0.6689341 , 0.3418185 ],
       [0.38439852, 0.6484475 , 0.49890193],
       [0.37452745, 0.616537  , 0.52580756]], dtype=float32)>

## Deep Neural Network 만들기

### keras.Sequential를 사용해 모델 만들기

In [8]:
import numpy as np
X=np.random.rand(1,5)

In [11]:
model = keras.Sequential([
    layers.Dense(3, input_shape=[5], activation='relu'),
    #layers.Dense(1, activation='relu')
])

In [12]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 3)                 18        
                                                                 
Total params: 18
Trainable params: 18
Non-trainable params: 0
_________________________________________________________________


In [13]:
model(X)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0., 0., 0.]], dtype=float32)>

### 모델에 층 추가하기

In [14]:
X=np.random.rand(1,10)

In [16]:
model = keras.Sequential([
    layers.Dense(5, input_shape=[10], activation='relu'),
#     layers.Dense(3, input_shape=[5], activation='relu')
    layers.Dense(3, activation='sigmoid')
])
model.compile()

In [17]:
# 패러미터의 갯수가 왜 저렇게 나오는지 생각해 볼것
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_7 (Dense)             (None, 5)                 55        
                                                                 
 dense_8 (Dense)             (None, 3)                 18        
                                                                 
Total params: 73
Trainable params: 73
Non-trainable params: 0
_________________________________________________________________


In [18]:
model(X)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.57556623, 0.71308035, 0.62933326]], dtype=float32)>

### 딥뉴럴 네트워크

In [19]:
model = keras.Sequential([
    layers.Dense(5, input_shape=[10], activation='relu'),
    layers.Dense(10,  activation='relu'), 
    layers.Dense(10,  activation='relu'), 
    layers.Dense(1,  activation='relu')
])
model.compile()

In [20]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_9 (Dense)             (None, 5)                 55        
                                                                 
 dense_10 (Dense)            (None, 10)                60        
                                                                 
 dense_11 (Dense)            (None, 10)                110       
                                                                 
 dense_12 (Dense)            (None, 1)                 11        
                                                                 
Total params: 236
Trainable params: 236
Non-trainable params: 0
_________________________________________________________________


## 다양한 layer
- Convolution Layer
- LSTM Layer
- Embedding Layer..
